### PR TITLE
Fix #82: QueryMultiSeriesAsync should return "partial" 

### LINKED ISSUE #82: QueryMultiSeriesAsync should return "partial" if responses are truncated by InfluxDB
InfluxDB offers the possibility to restrict the amount of rows returned by a (multi-)query. In order to do so, you need to set the configuration variable `max-row-limit` to a value `> 0`.

If a result is truncated because of this, InfluxDB indicates it by returning ```partial: true``` in the response. See https://docs.influxdata.com/influxdb/v1.7/administration/config/ , section "max-row-limit" for details.

I'd be happy to provide a pull request to your library that includes this information in QueryMultiSeriesAsync , but I'm not really sure how this information would fit best into the current response model. Would it be OK to include an additional field ` bool? partial` in `IInfluxSeries` and to optionally set this field in _every_ instance of IInfluxSeries if InfluxDB truncated a response?

### PR DESCRIPTION
**Pull request by tbraun-hk**
This pull request is an attempt to implement #82 
If InfluxDB is configured to have a "max-row-limit", then InfluxDB will return the flag "partial=true" to indicate that a response has been truncated due to the max-row-limit.

With this pull request, the "partial" flag is included in the IInfluxSeries and set according to the influx raw response.
A unit test that verifies the changes has been implemented, too. However, you need to have an InfluxDB system with max-row-limit set to 100.000 for this test to succeed.

### CODE REVIEW

**Comment by tbraun-hk** [comment]
The checks are failing because InfluxDB needs a special configuration for a new test to succeed (or we could remove the test, but I think it would be better to explicitly test the new functionality).

**Comment by mvadu** [comment]
You seems to be busy coding.. Thank you for your contribution. I am stuck with work and personal stuff.. I will probably review this over weekend.

**Comment by tbraun-hk** [comment]
Hi @mvadu sorry, we did not know that all the changes in our fork would be included in this PR, this was not our intention... I'll reopen another pull request. Please ignore this one and sorry for the circumstances...

**Comment by mvadu** [comment]
@tbraun-hk are you going submit the partial flag part of this PR?

**Comment by tbraun-hk** [comment]
Hi @mvadu yes, you are right. Sorry for taking so long, I'll open another pull request in the next couple of days.

**Pull request closed without merging**
