### PR TITLE
Fix #82: QueryMultiSeriesAsync should return "partial"

### LINKED ISSUE #82: QueryMultiSeriesAsync should return "partial" if responses are truncated by InfluxDB
InfluxDB offers the possibility to restrict the amount of rows returned by a (multi-)query. In order to do so, you need to set the configuration variable `max-row-limit` to a value `> 0`.

If a result is truncated because of this, InfluxDB indicates it by returning ```partial: true``` in the response. See https://docs.influxdata.com/influxdb/v1.7/administration/config/ , section "max-row-limit" for details.

I'd be happy to provide a pull request to your library that includes this information in QueryMultiSeriesAsync , but I'm not really sure how this information would fit best into the current response model. Would it be OK to include an additional field ` bool? partial` in `IInfluxSeries` and to optionally set this field in _every_ instance of IInfluxSeries if InfluxDB truncated a response?

### PR DESCRIPTION
**Pull request by tbraun-hk**
This pull request is another attempt to implement #82
If InfluxDB is configured to have a "max-row-limit", then InfluxDB will return the flag "partial=true" to indicate that a response has been truncated due to the max-row-limit.

With this pull request, the "partial" flag is included in the IInfluxSeries and set according to the influx raw response.
A unit test that verifies the changes has been implemented, too. However, you need to have an InfluxDB system with max-row-limit set to 100.000 for this test to succeed.

### CODE REVIEW

**Comment by mvadu** [comment]
Hi @tbraun-hk its been a long time since you sent this PR. Unfortunately I was little held up with life! Can you please check "**Allow edits from maintainers**" ([refer github help](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) so that I can fix the test data setup script (and change log) so that we can take this PR forward?

**Comment by tbraun-hk** [comment]
Hi @mvadu 

I'm sorry but due to the fact that I forked your repository from my organizations account, I'm unable to give you as maintainer access to the fork as described in the link (seems to be a known github issue: https://github.com/isaacs/github/issues/1681). 
Instead, I've added you as a contributor to my fork so that you are able to work on the branch. Thanks a lot for maintaining this library, by the way. I really like it a lot, because it's very lean, easy to understand and use and works very good for our use cases!

Best regards,
Tobias

**Comment by mvadu** [comment]
@tbraun-hk Hi Tobias, I have merged the PR. Thanks a lot for kind words about the library and for your contributions. Feel free to delete the branch on your repo.

**Comment by tbraun-hk** [comment]
Hi @mvadu that's great news, thanks a lot! I'll delete the branch on my repository.

**Pull request merged**
