### PR TITLE
Adding support for custom HTTP Request Headers

### PR DESCRIPTION
**Pull request by willwhite1**
- It would be nice to allow custom HTTP headers to be sent with the requests we target at Influx.

### CODE REVIEW

**Comment by willwhite1** [comment]
Thanks for the review and merge @mvadu . Do you have any timescales as to when a release inclusive of this changeset can be created? Thanks for the awesome library too.

**Comment by mvadu** [comment]
Hi @willwhite1 sorry for delay in response. I am waiting for another PR to get fixed. If not done by this weekend I will implement the suggested logic and push a nuget update.

**Comment by mvadu** [comment]
@willwhite1 new version pushed to Nuget today.

**Comment by willwhite1** [comment]
You rock!!! Thanks so much.

**Pull request merged**
